elements = {
    1: {"symbol": "H", "name": "Hydrogen"},
    2: {"symbol": "He", "name": "Helium"},
    3: {"symbol": "Li", "name": "Lithium"},
    4: {"symbol": "Be", "name": "Beryllium"},
    5: {"symbol": "B", "name": "Boron"},
    6: {"symbol": "C", "name": "Carbon"},
    7: {"symbol": "N", "name": "Nitrogen"},
    8: {"symbol": "O", "name": "Oxygen"},
    9: {"symbol": "F", "name": "Fluorine"},
    10: {"symbol": "Ne", "name": "Neon"},
    11: {"symbol": "Na", "name": "Sodium"},
    12: {"symbol": "Mg", "name": "Magnesium"},
    13: {"symbol": "Al", "name": "Aluminum"},
    14: {"symbol": "Si", "name": "Silicon"},
    15: {"symbol": "P", "name": "Phosphorus"},
    16: {"symbol": "S", "name": "Sulfur"},
    17: {"symbol": "Cl", "name": "Chlorine"},
    18: {"symbol": "Ar", "name": "Argon"},
    19: {"symbol": "K", "name": "Potassium"},
    20: {"symbol": "Ca", "name": "Calcium"},
    21: {"symbol": "Sc", "name": "Scandium"},
    22: {"symbol": "Ti", "name": "Titanium"},
    23: {"symbol": "V", "name": "Vanadium"},
    24: {"symbol": "Cr", "name": "Chromium"},
    25: {"symbol": "Mn", "name": "Manganese"},
    26: {"symbol": "Fe", "name": "Iron"},
    27: {"symbol": "Co", "name": "Cobalt"},
    28: {"symbol": "Ni", "name": "Nickel"},
    29: {"symbol": "Cu", "name": "Copper"},
    30: {"symbol": "Zn", "name": "Zinc"},
    31: {"symbol": "Ga", "name": "Gallium"},
    32: {"symbol": "Ge", "name": "Germanium"},
    33: {"symbol": "As", "name": "Arsenic"},
    34: {"symbol": "Se", "name": "Selenium"},
    35: {"symbol": "Br", "name": "Bromine"},
    36: {"symbol": "Kr", "name": "Krypton"},
    37: {"symbol": "Rb", "name": "Rubidium"},
    38: {"symbol": "Sr", "name": "Strontium"},
    # 39: {"symbol": "Y", "name": "Yttrium"},
    # 40: {"symbol": "Zr", "name": "Zirconium"},
    # 41: {"symbol": "Nb", "name": "Niobium"},
    # 42: {"symbol": "Mo", "name": "Molybdenum"},
    # 43: {"symbol": "Tc", "name": "Technetium"},
    # 44: {"symbol": "Ru", "name": "Ruthenium"},
    # 45: {"symbol": "Rh", "name": "Rhodium"},
    # 46: {"symbol": "Pd", "name": "Palladium"},
    47: {"symbol": "Ag", "name": "Silver"},
    # 48: {"symbol": "Cd", "name": "Cadmium"},
    # 49: {"symbol": "In", "name": "Indium"},
    50: {"symbol": "Sn", "name": "Tin"},
    51: {"symbol": "Sb", "name": "Antimony"},
    # 52: {"symbol": "Te", "name": "Tellurium"},
    53: {"symbol": "I", "name": "Iodine"},
    54: {"symbol": "Xe", "name": "Xenon"},
    55: {"symbol": "Cs", "name": "Cesium"},
    56: {"symbol": "Ba", "name": "Barium"},
    57: {"symbol": "La", "name": "Lanthanum"},
    # 58: {"symbol": "Ce", "name": "Cerium"},
    # 59: {"symbol": "Pr", "name": "Praseodymium"},
    # 60: {"symbol": "Nd", "name": "Neodymium"},
    # 61: {"symbol": "Pm", "name": "Promethium"},
    # 62: {"symbol": "Sm", "name": "Samarium"},
    # 63: {"symbol": "Eu", "name": "Europium"},
    # 64: {"symbol": "Gd", "name": "Gadolinium"},
    # 65: {"symbol": "Tb", "name": "Terbium"},
    # 66: {"symbol": "Dy", "name": "Dysprosium"},
    # 67: {"symbol": "Ho", "name": "Holmium"},
    # 68: {"symbol": "Er", "name": "Erbium"},
    # 69: {"symbol": "Tm", "name": "Thulium"},
    # 70: {"symbol": "Yb", "name": "Ytterbium"},
    # 71: {"symbol": "Lu", "name": "Lutetium"},
    # 72: {"symbol": "Hf", "name": "Hafnium"},
    # 73: {"symbol": "Ta", "name": "Tantalum"},
    74: {"symbol": "W", "name": "Tungsten"},
    # 75: {"symbol": "Re", "name": "Rhenium"},
    # 76: {"symbol": "Os", "name": "Osmium"},
    # 77: {"symbol": "Ir", "name": "Iridium"},
    78: {"symbol": "Pt", "name": "Platinum"},
    79: {"symbol": "Au", "name": "Gold"},
    80: {"symbol": "Hg", "name": "Mercury"},
    # 81: {"symbol": "Tl", "name": "Thallium"},
    82: {"symbol": "Pb", "name": "Lead"},
    83: {"symbol": "Bi", "name": "Bismuth"},
    84: {"symbol": "Po", "name": "Polonium"},
    # 85: {"symbol": "At", "name": "Astatine"},
    86: {"symbol": "Rn", "name": "Radon"},
    87: {"symbol": "Fr", "name": "Francium"},
    88: {"symbol": "Ra", "name": "Radium"},
    89: {"symbol": "Ac", "name": "Actinium"},
    90: {"symbol": "Th", "name": "Thorium"},
    # 91: {"symbol": "Pa", "name": "Protactinium"},
    92: {"symbol": "U", "name": "Uranium"},
    # 93: {"symbol": "Np", "name": "Neptunium"},
    94: {"symbol": "Pu", "name": "Plutonium"},
    # 95: {"symbol": "Am", "name": "Americium"},
    # 96: {"symbol": "Cm", "name": "Curium"},
    # 97: {"symbol": "Bk", "name": "Berkelium"},
    # 98: {"symbol": "Cf", "name": "Californium"},
    # 99: {"symbol": "Es", "name": "Einsteinium"},
    # 100: {"symbol": "Fm", "name": "Fermium"},
    # 101: {"symbol": "Md", "name": "Mendelevium"},
    # 102: {"symbol": "No", "name": "Nobelium"},
    # 103: {"symbol": "Lr", "name": "Lawrencium"},
    # 104: {"symbol": "Rf", "name": "Rutherfordium"},
    # 105: {"symbol": "Db", "name": "Dubnium"},
    # 106: {"symbol": "Sg", "name": "Seaborgium"},
    # 107: {"symbol": "Bh", "name": "Bohrium"},
    # 108: {"symbol": "Hs", "name": "Hassium"},
    # 109: {"symbol": "Mt", "name": "Meitnerium"},
    # 110: {"symbol": "Ds", "name": "Darmstadtium"},
    # 111: {"symbol": "Rg", "name": "Roentgenium"},
    # 112: {"symbol": "Cn", "name": "Copernicium"},
    # 113: {"symbol": "Nh", "name": "Nihonium"},
    # 114: {"symbol": "Fl", "name": "Flerovium"},
    # 115: {"symbol": "Mc", "name": "Moscovium"},
    # 116: {"symbol": "Lv", "name": "Livermorium"},
    # 117: {"symbol": "Ts", "name": "Tennessine"},
    # 118: {"symbol": "Og", "name": "Oganesson"}
}

polyatomic = {
    "NH4+": {"symbol": "NH4+", "name": "ammonium"},
    "OH-": {"symbol": "OH-", "name": "hydroxide"},
    "NO3-": {"symbol": "NO3-", "name": "nitrate"},
    "NO2-": {"symbol": "NO2-", "name": "nitrite"},
    "SO4^2-": {"symbol": "SO4^2-", "name": "sulfate"},
    "SO3^2-": {"symbol": "SO3^2-", "name": "sulfite"},
    "CO3^2-": {"symbol": "CO3^2-", "name": "carbonate"},
    "HCO3-": {"symbol": "HCO3-", "name": "bicarbonate"},
    "PO4^3-": {"symbol": "PO4^3-", "name": "phosphate"},
    "CH3C00-": {"symbol": "C2H3O2-", "name": "acetate"},
    "ClO3-": {"symbol": "ClO3-", "name": "chlorate"},
    "ClO4-": {"symbol": "ClO4-", "name": "perchlorate"},
    "MnO4-": {"symbol": "MnO4-", "name": "permanganate"},
    # "C2O4^2-": {"symbol": "C2O4^2-", "name": "oxalate"},
    "CrO4^2-": {"symbol": "CrO4^2-", "name": "chromate"},
    "Cr2O7^2-": {"symbol": "Cr2O7^2-", "name": "dichromate"},
    "HSO4-": {"symbol": "HSO4-", "name": "hydrogen sulfate"},
    "HSO3-": {"symbol": "HSO3-", "name": "hydrogen sulfite"},
    "CN-": {"symbol": "CN-", "name": "cyanide"},
    "O2^2-": {"symbol": "O2^2-", "name": "peroxide"},
    "S2O3^2-": {"symbol": "S2O3^2-", "name": "thiosulfate"},
    "SCN-": {"symbol": "SCN-", "name": "thiocyanate"},
    "CrO3^2-": {"symbol": "CrO3^2-", "name": "perchromate"},
    "NH2-": {"symbol": "NH2-", "name": "amide"},
    "NO2+": {"symbol": "NO2+", "name": "nitronium"},
    "CLO2-": {"symbol": "CLO2-", "name": "chlorite"},
    "CLO-": {"symbol": "CLO-", "name": "hypochlorite"},
    "MnO3-": {"symbol": "MnO3-", "name": "manganate"},
    "IO-": {"symbol": "IO-", "name": "hypoiodite"},
    "IO2-": {"symbol": "IO2-", "name": "iodite"},
    "IO3-": {"symbol": "IO3-", "name": "iodate"},
    "IO4-": {"symbol": "IO4-", "name": "periodate"},
    "BO3^3-": {"symbol": "BO3^3-", "name": "borate"},
    "HS-": {"symbol": "HS-", "name": "hydrogen sulfide"},
    "HS2O3-": {"symbol": "HS2O3-", "name": "dithionite"},
    "H2PO4-": {"symbol": "H2PO4-", "name": "dihydrogen phosphate"},
    "HPO4^2-": {"symbol": "HPO4^2-", "name": "hydrogen phosphate"},
    "H2AsO4-": {"symbol": "H2AsO4-", "name": "dihydrogen arsenate"},
    "HAsO4^2-": {"symbol": "HAsO4^2-", "name": "hydrogen arsenate"},
    "HSiO3-": {"symbol": "HSiO3-", "name": "hydrogen silicate"},
    "HSiO4^2-": {"symbol": "HSiO4^2-", "name": "silicic acid"},
    "HC2O4-": {"symbol": "HC2O4-", "name": "hydrogen oxalate"},
    "CLO4-": {"symbol": "CLO4-", "name": "perchlorate"},
    "C2H3O2-": {"symbol": "C2H3O2-", "name": "acetate"},
    "C2O4^2-": {"symbol": "C2O4^2-", "name": "oxalate"},
    "HPO3^2-": {"symbol": "HPO3^2-", "name": "hypophosphite"},
    "H2PO3-": {"symbol": "H2PO3-", "name": "dihydrogen phosphite"},
    "BO2-": {"symbol": "BO2-", "name": "hydrogen borate"},
    "B4O7^2-": {"symbol": "B4O7^2-", "name": "tetraborate"}
}
